<?php

function openid_connect_wild_apricot_openid_connect_post_authorize($account, $context) {
  $userinfo = $context['userinfo'];

  $config = \Drupal::service('config.factory')->get('openid_connect.settings.wild_apricot');
  $membership_level_bindings = $config->get('membership_level_bindings');

  $membership_level = isset($userinfo['MembershipLevel']) 
                      && isset($userinfo['MembershipLevel']['Id'])
                      && isset($userinfo['Status'])
                      && in_array($userinfo['Status'], array('Active', 'PendingRenewal'))
                       ? $userinfo['MembershipLevel']['Id'] 
                       : NULL;

  $roles = $account->getRoles();

  $updated = false;

  foreach (user_roles(TRUE) as $rid => $role) {
    if ($rid == 'authenticated') continue;
    if (isset($membership_level_bindings['__ignore__']) &&
        in_array($rid, $membership_level_bindings['__ignore__'])) continue;

    if (isset($membership_level_bindings[$membership_level])) {
      if (in_array($rid, $membership_level_bindings[$membership_level])) {
        if (!in_array($rid, $roles)) {
          $account->addRole($rid);
          $updated = true;
        }
      } else if (in_array($rid, $roles)) {
        $account->removeRole($rid);
        $updated = true;
      }
    } 
  }

  if ($updated) {
    $account->save();
  }
}
